name: autoticket
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - opencv
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pip:
    - fastapi
    - uvicorn
    - dash
    - ultralytics
    - easyocr