name: autoticket
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - matplotlib
  - seaborn
  - fastapi
  - uvicorn
  - dash
  - pip:
    - ultralytics
    - label-studio
    - label-studio-sdk
    - tqdm
    - python-multipart